### ISSUE TITLE
PDF: Chapter 6 missing from table of contents and page 29 heading

### ISSUE THREAD

**Issue by clobber** [jflaherty/ptrtut13#1]
Thanks for the great LaTeX and Markdown conversions of this classic. In the PDF, Chapter 6 is missing in the table of contents as well as the heading which I believe is due to a missing `\subsection` in ch6x.tx https://github.com/jflaherty/ptrtut13/blob/66cd0d6da0abfa4d431ea5c2eb165ba3942e09cc/tex/ch6x.tex#L2

NOTE: fixing this will mean you want to also adjust the spacing on the TOC page, as the last entry will be pushed off onto a new page.

**Comment by jflaherty** [comment]
Thank you so much for opening this issue. Just noticed this tonight. Not sure why I did not get notified. Hopefully it will be an easy fix. A little worried about how to get the spacing right on the TOC page.

**Comment by jflaherty** [comment]
Fix missing ch6 subsection and TOC entry
    
    I think there was an issue with the pandoc app converting html to LaTex for chapter 6.
    Specifically with the missing subsection tag. This in turn caused the TOC to get generated
    without chapter 6 referenced. This has been corrected as well as some cleanup to the
    TOC file (delete  subsubsections) as well as taking the center tag out of pointers.htm
